[package]
name = "jwt-practice"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.89"
jsonwebtoken = "10.3.0"
serde_json = "1.0.128"
